// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function LoadFileRequest(arg1:string):Promise<void>;

export function PauseRequest():Promise<void>;

export function PlayNextReques():Promise<void>;

export function PlayPreviousReques():Promise<void>;

export function PlayRandomReques():Promise<void>;

export function PlayRequest():Promise<void>;

export function SeekToReques(arg1:number):Promise<void>;

export function SetVolumeReques(arg1:number):Promise<void>;

export function StopRequest():Promise<void>;
